[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:8000 --workers 4 --worker-class uvicorn.workers.UvicornWorker"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 